opencb/cellbase

cellbase-app/build/bin/ensembl-scripts/DB_CONFIG.pm
cellbase-app/src/main/java/org/opencb/cellbase/app/cli/DownloadCommandParser.java

- Changed "our sub" to "sub" in DB_CONFIG.pm (for compatibility with perl 2.18.x)
- DownloadCommandParser improvements:
- Added Log file to perl scripts
- Refactored ProcessBuilder calls
- Improved ProcessBuilder error output handling

Downloader Improvements

---

cellbase-app/src/main/java/org/opencb/cellbase/app/cli/DownloadCommandParser.java

DownloadCommandParser:
- Gene .gtf file added
- Some small refactorization

DownloadCommandParser: download of gene .gtf file added

---

cellbase-core/src/main/java/org/opencb/cellbase/core/client/CellBaseClient.java
cellbase-core/src/test/java/org/opencb/cellbase/core/client/CellBaseClientTest.java

Just add an entry "post=true" to the QueryOptions

CellBaseClient can now query with POST method.

---

cellbase-app/src/main/java/org/opencb/cellbase/app/transform/VariationParser.java

Variation Parser:
- Fixed transcript_variation variable column number issue
- Added support for zipped/unzipped input files

VariationParser: fixed bug

---

cellbase-app/src/main/java/org/opencb/cellbase/app/cli/CliOptionsParser.java

Build CLI: Fixed 'data' parameter description

---

cellbase-server/src/main/java/org/opencb/cellbase/server/ws/genomic/RegionWSServer.java

Changed "phenotpe" for "phenotype" in RegionWSServer "getClinicalByRegion"
closes #139

Fixed typo

---

cellbase-app/src/main/java/org/opencb/cellbase/app/transform/VariationParser.java

-Added ExAC frequencies
-Removed unused phase 3 population 'ASN'
-Changed some tags in frequencies input file

VariationParser: added ExAC frequencies

---

cellbase-app/src/main/java/org/opencb/cellbase/app/transform/variation/VariationParser.java
cellbase-mongodb/src/main/java/org/opencb/cellbase/mongodb/db/variation/VariantAnnotationMongoDBAdaptor.java

-  Updated VariantAnnotation model
-  Removed superpopulations from PopulationFrequencies

Updated VariantAnnotation model

---

cellbase-client/src/main/java/org/opencb/cellbase/client/rest/CellBaseClient.java
cellbase-client/src/main/java/org/opencb/cellbase/client/rest/FeatureClient.java
cellbase-client/src/main/java/org/opencb/cellbase/client/rest/GeneClient.java
cellbase-client/src/main/java/org/opencb/cellbase/client/rest/GenomicRegionClient.java
cellbase-client/src/main/java/org/opencb/cellbase/client/rest/ParentRestClient.java
cellbase-client/src/main/java/org/opencb/cellbase/client/rest/ProteinClient.java
cellbase-client/src/main/java/org/opencb/cellbase/client/rest/TranscriptClient.java
cellbase-client/src/main/java/org/opencb/cellbase/client/rest/VariantClient.java
cellbase-client/src/main/java/org/opencb/cellbase/client/rest/VariationClient.java

client: Accept assembly in the CellBaseClient. Closes #311

---

clients/python/HISTORY.rst
clients/python/README.rst
clients/python/pycellbase/cbrestclients.py
clients/python/pycellbase/commons.py
clients/python/setup.py
clients/python/use_case.ipynb

- Added Jupyter Notebook with use case
- Fixed debug option when option is None
- Added ImportError handling when importing setuptools
- Updated docs

PyCellBase 4.5.2

---

clients/python/HISTORY.rst
clients/python/setup.py

This was added to requirements but need to be separately added to setup.py, I missed that there are two dependency lists.

Add retrying to setup.py

---

cellbase-core/src/main/resources/configuration.json
cellbase-lib/src/main/java/org/opencb/cellbase/lib/impl/MongoDBAdaptorFactory.java
pom.xml

lib: Fix MongoCredentials creation to allow ssl connections. #389

---

cellbase-core/src/main/java/org/opencb/cellbase/core/config/CellBaseConfiguration.java
cellbase-core/src/test/java/org/opencb/cellbase/core/config/CellBaseConfigurationTest.java

Add support for database configuration using environment variables

---

checkstyle.xml
pom.xml

Update Maven Checkstyle plugin to latest version. Refs #409
Made some syntax changes based on checkstyle release notes.
Copyright header will be updated - that's a separate ticket

Update Maven Checkstyle plugin to latest version.

---

README.md

I noticed this issue on your github, and I feel like it's a pretty insignificant change, but at least I hope you can close another issue on your list. All the best!

441 consolidate docs

---

cellbase-lib/src/main/java/org/opencb/cellbase/lib/managers/VariantManager.java
cellbase-lib/src/main/java/org/opencb/cellbase/lib/variant/annotation/VariantAnnotationCalculator.java
cellbase-lib/src/test/java/org/opencb/cellbase/lib/variant/VariantManagerTest.java
cellbase-server/src/main/java/org/opencb/cellbase/server/rest/genomic/VariantWSServer.java

merging our new end points:
`/{apiVersion}/{species}/genomic/variant/{variants}/normalization`
`/{apiVersion}/{species}/genomic/variant/{variants}/hgvs `
@javild please test, also not sure if I got the path right.

Hgvs normalization api

---

cellbase-lib/src/main/java/org/opencb/cellbase/lib/builders/clinical/variant/ClinVarIndexer.java
cellbase-lib/src/main/java/org/opencb/cellbase/lib/variant/annotation/ConsequenceTypeGenericRegionCalculator.java
cellbase-lib/src/main/java/org/opencb/cellbase/lib/variant/annotation/VariantAnnotationCalculator.java
cellbase-lib/src/main/java/org/opencb/cellbase/lib/variant/hgvs/HgvsCalculator.java
cellbase-lib/src/main/java/org/opencb/cellbase/lib/variant/hgvs/HgvsProteinCalculator.java
cellbase-lib/src/main/java/org/opencb/cellbase/lib/variant/hgvs/HgvsTranscriptCalculator.java
cellbase-lib/src/main/java/org/opencb/cellbase/lib/variant/hgvs/TranscriptUtils.java

See #555 for the original pull request. All of my fixes in v4 merged into v5.

Merge v4 fixes into v5

---

cellbase-client/src/main/python/pycellbase/cbconfig.py
cellbase-client/src/main/python/pycellbase/commons.py

This PR includes the next changes:
- Added backwards compatibility for response and result

Add backwards compatibility for response and result

---

cellbase-app/pom.xml
cellbase-client/pom.xml
cellbase-core/pom.xml
cellbase-lib/pom.xml
cellbase-server/pom.xml
cellbase-test/pom.xml
pom.xml

replaced the incompatible jackson version by downgrading to 2.10.5

downgrade jackson version #TASK-1774

---

cellbase-app/pom.xml
cellbase-app/src/main/java/org/opencb/cellbase/app/cli/DownloadCommandExecutor.java
cellbase-app/src/main/java/org/opencb/cellbase/app/cli/EtlCommons.java
cellbase-app/src/main/java/org/opencb/cellbase/app/cli/QueryGrpcCommandExecutor.java
cellbase-app/src/main/java/org/opencb/cellbase/app/cli/ValidationCommandExecutor.java
cellbase-app/src/main/java/org/opencb/cellbase/app/cli/VariantAnnotationCommandExecutor.java
cellbase-app/src/main/java/org/opencb/cellbase/app/cli/variant/annotation/JsonStringAnnotatorTask.java
cellbase-app/src/main/java/org/opencb/cellbase/app/transform/GeneParser.java
cellbase-app/src/main/java/org/opencb/cellbase/app/transform/clinical/variant/DOCMIndexer.java
cellbase-app/src/main/java/org/opencb/cellbase/app/transform/clinical/variant/GwasParser.java
cellbase-app/src/test/java/org/opencb/cellbase/app/transform/DgvParserTest.java
cellbase-app/src/test/java/org/opencb/cellbase/app/transform/RepeatsParserTest.java
cellbase-client/pom.xml
cellbase-client/src/main/java/org/opencb/cellbase/client/grpc/CellbaseGrpcClient.java
cellbase-core/pom.xml
cellbase-core/src/main/java/org/opencb/cellbase/core/variant/annotation/hgvs/HgvsCalculator.java
cellbase-core/src/main/java/org/opencb/cellbase/core/variant/annotation/hgvs/HgvsTranscriptCalculator.java
cellbase-core/src/test/java/org/opencb/cellbase/core/variant/annotation/hgvs/HgvsProteinCalculatorTest.java
cellbase-lib/pom.xml
cellbase-lib/src/main/java/org/opencb/cellbase/lib/impl/GeneMongoDBAdaptor.java
cellbase-lib/src/test/java/org/opencb/cellbase/lib/impl/ClinicalMongoDBAdaptorTest.java
cellbase-lib/src/test/java/org/opencb/cellbase/lib/variant/annotation/hgvs/HgvsTranscriptCalculatorTest.java
pom.xml

Revert "Task 1625"

---

cellbase-client/src/main/python/pycellbase/commons.py

TASK-2154 - Pycellbase error when handling query results

---

cellbase-lib/src/main/java/org/opencb/cellbase/lib/variant/annotation/VariantAnnotationCalculator.java

I've fixed this in v4 but also need this fix in v5.

remove static to fix concurrency issues

---

cellbase-client/src/main/java/org/opencb/cellbase/client/rest/CellBaseClient.java
cellbase-client/src/main/java/org/opencb/cellbase/client/rest/ClinicalVariantClient.java
cellbase-client/src/main/java/org/opencb/cellbase/client/rest/FeatureClient.java
cellbase-client/src/main/java/org/opencb/cellbase/client/rest/GeneClient.java
cellbase-client/src/main/java/org/opencb/cellbase/client/rest/GenericClient.java
cellbase-client/src/main/java/org/opencb/cellbase/client/rest/GenomicRegionClient.java
cellbase-client/src/main/java/org/opencb/cellbase/client/rest/MetaClient.java
cellbase-client/src/main/java/org/opencb/cellbase/client/rest/ParentRestClient.java
cellbase-client/src/main/java/org/opencb/cellbase/client/rest/ProteinClient.java
cellbase-client/src/main/java/org/opencb/cellbase/client/rest/TranscriptClient.java
cellbase-client/src/main/java/org/opencb/cellbase/client/rest/VariantClient.java
cellbase-client/src/main/java/org/opencb/cellbase/client/rest/VariationClient.java
cellbase-core/src/main/java/org/opencb/cellbase/core/models/DataRelease.java
cellbase-core/src/main/java/org/opencb/cellbase/core/models/DataReleaseSource.java

Use dataRelease from Cellbase in OpenCGA

TASK-1201 - Use dataRelease from Cellbase in OpenCGA

---

cellbase-app/src/main/java/org/opencb/cellbase/app/cli/admin/executors/LoadCommandExecutor.java

TASK-2579 Fix PubMed data loading

---

.github/workflows/develop.yml
.github/workflows/release.yml
.github/workflows/task.yml
.github/workflows/test-analysis.yml

TASK-3953 - CI/CD in task.yml to deploy project dependencies

---

.github/workflows/develop.yml
.github/workflows/release.yml
.github/workflows/task.yml
.github/workflows/test-analysis.yml

TASK-3991 - Release CI/CD workflow should put results of test on xetabase dir on report server

---

pom.xml

Update java-common-libs dependency.

TASK-4171 Fix MongoDB driver in cellbase 5.1

---

cellbase-app/src/main/java/org/opencb/cellbase/app/cli/main/CellBaseCliOptionsParser.java
cellbase-app/src/main/java/org/opencb/cellbase/app/cli/main/executors/VariantAnnotationCommandExecutor.java
cellbase-app/src/test/java/org/opencb/cellbase/app/cli/VariantAnnotationCommandExecutorTest.java
cellbase-core/src/main/java/org/opencb/cellbase/core/ParamConstants.java
cellbase-lib/src/main/java/org/opencb/cellbase/lib/managers/VariantManager.java
cellbase-lib/src/main/java/org/opencb/cellbase/lib/variant/annotation/VariantAnnotationCalculator.java
cellbase-lib/src/test/java/org/opencb/cellbase/lib/impl/core/VariantAnnotationCalculatorTest.java
cellbase-lib/src/test/java/org/opencb/cellbase/lib/variant/VariantManagerTest.java
cellbase-server/src/main/java/org/opencb/cellbase/server/rest/genomic/VariantWSServer.java

Fix default parameters for the normalization config

TASK-4530 Fix CellBase normalization configuration

---

cellbase-client/src/test/java/org/opencb/cellbase/client/rest/VariantClientTest.java

TASK-5025 CellBase CI/CD fails due to a JUnit test error

---

cellbase-app/src/main/java/org/opencb/cellbase/app/cli/admin/AdminCliOptionsParser.java
cellbase-app/src/main/java/org/opencb/cellbase/app/cli/admin/executors/ApiKeyCommandExecutor.java

TASK-4988 Fix CellBase CLI to create API keys that only include a quota

---

cellbase-lib/src/main/java/org/opencb/cellbase/lib/builders/clinical/variant/HGMDIndexer.java
cellbase-lib/src/main/java/org/opencb/cellbase/lib/variant/annotation/VariantAnnotationCalculator.java

TASK-5212 Fix 'cellbase-admin.sh build' for clinical variants

---

cellbase-lib/src/main/java/org/opencb/cellbase/lib/impl/core/MetaMongoDBAdaptor.java
cellbase-server/src/main/java/org/opencb/cellbase/server/rest/GenericRestWSServer.java

Fix CellBase web services initialization

TASK-5340 Fix CellBase web services initialization

---

cellbase-lib/src/main/java/org/opencb/cellbase/lib/variant/annotation/VariantAnnotationCalculator.java

TASK-5457 Fix CellBase annotation queries for SV variants

---

cellbase-app/pom.xml
cellbase-client/pom.xml
cellbase-core/pom.xml
cellbase-lib/pom.xml
cellbase-server/pom.xml
pom.xml

TASK-5444 - Fix OpenCB repository versions to conform to XetaBase 2.0.0 version

TASK-5444 - Fix OpenCB repository versions to conform to XetaBase 2.0.0 version

---

cellbase-core/src/main/java/org/opencb/cellbase/core/ParamConstants.java
cellbase-server/src/main/java/org/opencb/cellbase/server/rest/MetaWSServer.java

[TASK-5704](https://app.clickup.com/t/36631768/TASK-5704)

Fix CellBase endpoint: meta/{species}/versions

---

.github/workflows/pull-request-approved.yml
.github/workflows/scripts/get-xetabase-branch.sh

TASK-6807 - Pull request approve workflow Fail

TASK-6807 - Pull request approve workflow Fail

---

.github/workflows/pull-request-approved.yml
.github/workflows/scripts/get-xetabase-branch.sh
cellbase-app/pom.xml
cellbase-client/pom.xml
cellbase-core/pom.xml
cellbase-lib/pom.xml
cellbase-server/pom.xml
pom.xml

TASK-6879 - Adapt GitHub Actions, CICD workflows and release scripts to new SDLC

TASK-6879 - Adapt GitHub Actions, CICD workflows and release scripts to new SDLC

---

pom.xml

Increase mongoDB driver version to support v7
[TASK-7155](https://app.clickup.com/t/8696cz8vg)

TASK-7155: Upgrade MongoDB to v7.0
